masuyu/36makuake

- Gemfile
- Gemfile.lock
- config/unicorn.rb
> unicornを追加

- config/database.yml
database.ymlを編集
EC2内にmakuakeDatabase作成のため
> database.ymlChenged

- app/assets/stylesheets/_supportindex.css.scss
- app/views/courseTemplate/_courseQuestions.html.haml
- app/views/courses/show.html.haml
コースの詳細画面を作成。
クラウドファンディングシステム・サービスに必須の機能のため。
> コース詳細画面を作成

- app/assets/stylesheets/_project-common.css.scss
- app/assets/stylesheets/_supportcheck.css.scss
- app/views/courses/show.html.haml
- app/views/orders/show.html.haml
オーダー詳細画面を実装。
クラウドファンディングシステム・サービスに必須の機能であるため。
> オーダー詳細画面を作成

- app/assets/stylesheets/application.scss
app/assets/stylesheets/application.scss
に一部追記。
Viewの見た目向上のため。
> application.scssに追記

- app/controllers/courses_controller.rb
- app/views/courseTemplate/_question.html.haml
- app/views/courses/show.html.haml
- app/views/orders/new.html.haml
- config/routes.rb
ルーティング・コントローラの設定。
Viewにインスタンス変数を記述。
Question部分のレンダリングを実施。
クレジット情報はOrderページで扱うため、本ページでの決済関連の情報は削除。
クラウドファンディングシステム・サービスに必須な機能であるため。
> コース詳細ページの修正１

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/unicorn.rb
Capistranoを導入。
自動デプロイ化して、:3000を外すため。
> capistrano導入

- app/assets/javascripts/project.js
- app/assets/stylesheets/_common.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_index.scss
- app/controllers/application_controller.rb
- app/views/layouts/_account_area.html.haml
- app/views/layouts/application.html.haml
- app/views/projects/index.html.haml
- app/views/shared/_header.html.haml
- app/views/template/_new.html.haml
- app/views/template/_pickup.html.haml
#WHAT
・ログイン、ログアウト時の表示の変更
・クリックで通知、マイメニューの表示
・ログイン、ログアウト、新規登録へのリンクの追加
・page-topボタンのjs追加等
> ヘッダーの編集+pagetopボタンのjs

- app/assets/javascripts/account.js
- app/assets/stylesheets/_account.scss
- app/assets/stylesheets/_admin.scss
- app/assets/stylesheets/_common.scss
- app/assets/stylesheets/application.scss
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/layouts/_flash_message.html.haml
- app/views/layouts/_sign_in.html.haml
- app/views/layouts/_sign_up.html.haml
ログインフォーム、サインアップフォームのビューにスタイルを当てる。
デザインをきれいにするため。
> ログイン・サインアップ用のビューの調整

- app/views/courses/show.html.haml
> show.html.haml修正インデント

- Gemfile
- Gemfile.lock
- config.ru
unicorn-worker-killerを導入する
デプロイ時のメモリ不足を解消するため
設定はこちらの記事を参考にしています。
https://qiita.com/k-shimoji/items/9d49e76dae2a97208c9c
https://zephiransas.github.io/blog/2015/07/29/unicorn-worker-killer/
> unicorn-worker-killerの導入

- config/deploy.rb
> 修正config/deploy.rb

- config/deploy.rb
> 修正capistrano

- config/unicorn.rb
before_exec do |server|
ENV['BUNDLE_GEMFILE'] = "#{current_path}/Gemfile"
end
を追記。
> 修正Unicorn.rb

- app/views/courseTemplate/_question.html.haml
_question.html.hamlに
CourseQuestionAnswerをラジオボタンで表示
回答選択をできるようにする為
> 修正_question.html.haml

- app/assets/javascripts/account.js
app/assets/javascripts/account.js
> 変更app/assets/javascripts/account.js

- app/views/users/consumed.html.haml
- app/views/users/edit.html.haml
- app/views/users/edit_password.html.haml
##What
マイページ関連HamlファイルのHeadを修正する。
##Why
必須の機能のため。
> マイページ関連HamlファイルのHead修正

- app/controllers/orders_controller.rb
- app/models/project.rb
- app/views/orders/create.html.haml
> 決済完了ページviewのみ

- config/environments/production.rb
config/environments/production.rb
> uglifier対策config/environments/production.rb

- config/deploy.rb
再起動の際に環境変数を読み込む設定を追加
サービスに必須なため
> unicorn設定config/deploy.rb

- app/controllers/courses_controller.rb
コースに紐づいた画像が表示されるように、画像の検索方法を修正
> コース詳細画面が表示できないエラーを修正

- app/controllers/orders_controller.rb
- app/models/order.rb
リファクタリング。
コードを綺麗にし見通しよくして、保守性を上げるため。
> Refactoring orders

- app/assets/javascripts/course_show.js
- app/views/courses/show.html.haml
- app/views/orders/new.html.haml
Send_addressがないユーザーに登録を促すモーダルを表示するJavaScriptを記述。
> Make order validation

- app/assets/javascripts/history.js
- app/views/layouts/application.html.haml
- app/views/projects/index.html.haml
- app/views/template/_history.html.haml
- app/views/template/_history_detail.html.haml
- app/views/template/_project.html.haml
トップページのスライダー下に、
ユーザーが閲覧したプロジェクトを5件表示する
> プロジェクト閲覧履歴の表示

- app/views/courses/show.html.haml
- app/views/template/_courses.html.haml
> Page position bug fix

- app/assets/stylesheets/project_froala.css
- app/assets/stylesheets/promoter_ver3.css
- app/views/promoter_profiles/_project.html.haml
- app/views/promoter_profiles/_supporter_detail.html.haml
> プロジェクト実行者用のページのレイアウト調整

- app/assets/javascripts/promoter.js
- app/assets/stylesheets/project_froala.css
- app/assets/stylesheets/promoter_ver3.css
- app/controllers/projects_controller.rb
- app/views/layouts/account.html.haml
- app/views/projects/_edit.html.haml
- app/views/projects/_update.html.haml
- app/views/projects/edit.js.erb
- app/views/projects/show.html.haml
- app/views/projects/update.js.erb
- config/routes.rb
プロジェクト詳細ページで、プロジェクト実行者が説明文を編集できる機能を追加
> プロジェクト機能のアップデート

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users/send_address.scss
- app/controllers/send_addresses_controller.rb
- app/views/devise/registrations/edit.html.haml
- app/views/send_addresses/_send_address.html.haml
- app/views/send_addresses/edit.html.haml
- app/views/send_addresses/index.html.haml
- app/views/send_addresses/new.html.haml
- app/views/shared/_sidenavi.html.haml
- app/views/users/consumed.html.haml
- app/views/users/edit.html.haml
- app/views/users/invest.html.haml
- app/views/users/leave.html.haml
- app/views/users/message.html.haml
- app/views/users/popup.html.haml
- app/views/users/show.html.haml
- config/routes.rb
##What
お届け先住所の登録・編集・一覧の実装（再送）
##Why
必須の機能のため。
> お届け先住所の登録・編集・一覧の実装（再送）

- app/controllers/application_controller.rb
> setBasicAuth

- app/controllers/users_controller.rb
> 新規登録フォームのajaxの修正

- app/uploaders/course_image_uploader.rb
- app/uploaders/project_image_uploader.rb
- app/uploaders/project_main_image_uploader.rb
- app/uploaders/user_image_uploader.rb
- config/initializers/carrierwave.rb
config/initializers/carrierwave.rb
app/uploaders/course_image_uploader.rb
app/uploaders/project_image_uploader.rb
app/uploaders/project_main_image_uploader.rb
app/uploaders/user_image_uploader.rb
> carrierwave本番環境/開発環境の使い分

- app/views/layouts/account.html.haml
- app/views/layouts/application.html.haml
> モバイル環境で閲覧した際のビューの設定

- app/assets/javascripts/account.js
- app/assets/stylesheets/promoter_ver3.css
- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/layouts/_sign_in.html.haml
- app/views/layouts/_sign_up.html.haml
- app/views/layouts/account.html.haml
- app/views/projects/show.html.haml
> windows環境での表示調整

- app/assets/javascripts/reject_querystring.js
- app/controllers/courses_controller.rb
- app/views/courses/show.html.haml
> クエリストリング排除

- app/controllers/project_likes_controller.rb
- app/views/project_likes/_project.html.haml
- app/views/project_likes/index.html.haml
- app/views/shared/_header.html.haml
- config/initializers/assets.rb
- config/routes.rb
> お気に入り一覧ページ
